name: Release

on:
  workflow_dispatch:
    inputs:
      forceVersion:
        description: 'Force version'
        required: false
        default: ''

jobs:
  release:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: ci

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: 'Previous version'
        if: github.ref == 'refs/heads/protect-master/hooks'
        id: 'previous-version'
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Release
        if: github.ref == 'refs/heads/protect-master/hooks'
        run: ./gradlew release -Prelease.customPassword=${GITHUB_TOKEN} -Prelease.customUsername=${GITHUB_ACTOR} -Prelease.forceVersion=${FORCE_VERSION}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_VERSION: ${{ github.event.inputs.forceVersion }}
      - name: Log new version
        id: 'next-version'
        run: |
          NEW_HERMES_VERSION="`./gradlew -q cV -Prelease.quiet`"
          echo "::set-output name=new_hermes_version::$NEW_HERMES_VERSION"
          echo "New Hermes version: ${NEW_HERMES_VERSION}"
